Fix CI
meilisearch/meilisearch-digitalocean pull request #219
Opened 2021-08-19 09:01 UTC by alallema

Droplet shutdown failed and return `errored`
Add power_off in case of Droplet shutdown return `errored`

2021-08-19 14:53 UTC, nicolasvienot approved these changes
LGTM! 

I remember we had previous issues with `droplet.shutdown` where it was randomly not shutting down the droplet. This had been fixed and I can't tell why this is happening every time now. If you ever find out I'd be interested 😄 

In the meantime, I think your workaround is clean, I don't think there is a problem with triggering `droplet.power_off` since we won't be using those instances anymore.

🎉

2021-08-19 14:53 UTC, nicolasvienot commented on tools/utils.py
> +                        destroy_droplet_and_exit(droplet)
I think you can raise the error here instead of using `destroy_droplet_and_exit(droplet)`

2021-08-19 14:53 UTC, nicolasvienot commented on tools/utils.py
> +        destroy_droplet_and_exit(droplet)
I think you can raise the error here instead of using `destroy_droplet_and_exit(droplet)`

2021-08-19 15:27 UTC, nicolasvienot requested changes
😇

2021-08-19 15:27 UTC, nicolasvienot commented on tools/utils.py
> +        destroy_droplet_and_exit(droplet)
```suggestion
        raise
```

2021-08-20 10:22 UTC, nicolasvienot approved these changes

2021-08-20 11:08 UTC, alallema commented
bors merge

2021-08-20 11:16 UTC, merged